version: "3"

silent: true

includes:
    tck:
        taskfile: ../../packages/tck/Taskfile.yml
        dir: ../../packages/tck

    tck-chai:
        taskfile: ../../packages/tck-chai/Taskfile.yml
        dir: ../../packages/tck-chai

tasks:
    default:
        deps:
            - build

    install:
        cmds:
            - pnpm i

    build:
        cmds:
            - task: install
            - task: format
            - task: lint
            - ./node_modules/.bin/babel src -d lib --out-file-extension .cjs

    clean:
        cmds:
            - rm -rf node_modules

    format:
        cmds:
            - ./node_modules/.bin/prettier "*.json" "src/*.js" --write > /dev/null

    lint:
        deps:
            - "lint:types"
            - "lint:format"
            - "lint:js"

    "lint:types":
        cmds:
            - ./node_modules/.bin/tsc

    "lint:format":
        cmds:
            - ./node_modules/.bin/prettier "*.json" "src/*.js" --check > /dev/null

    "lint:js":
        cmds:
            - ./node_modules/.bin/eslint --fix "src/*.js"

    test:
        deps:
            - "test:unit"

    "test:unit":
        deps:
            - "test:unit:node"

    "test:unit:node":
        cmds:
            - ./node_modules/.bin/mocha --inline-diffs -r @babel/register -r chai/register-expect.js "test/*.js" {{.CLI_ARGS}}

    update:
        cmds:
            - task: tck:build
            - task: tck-chai:build
            - task: build
